criacao issue template onboarding dta
transparencia-mg/handbook pull request #6
Opened 2021-04-26 14:11 UTC by gabrielbdornas

Conforme solicitação [Card Trello](https://trello.com/c/usZaSrio)

2021-04-26 14:20 UTC, gabrielbdornas commented
@fjuniorr solicito aprovaçao para inclusão da primeira versão do nosso issue template onboarding, conforme solicitado no [card trello](https://trello.com/c/usZaSrio). Proponho iniciarmos os trabalhos de revisão de código via GitHub. Sendo assim, caso você identifique algo a ser melhorado, me informe via pullrequest e não o faça diretamente no código. O que acha?

2021-04-27 14:55 UTC, Andrelamor requested changes
@gabrielbdornas sugiro verificar se não é o caso de incluir os itens para solicitação de acesso: Joomla, Armazém B.O., Mantis e Fale Conosco (BPMS PRODEMGE), ou se são sistemas de uso facultativo

2021-04-27 14:55 UTC, Andrelamor commented on .github/ISSUE_TEMPLATE/onboarding-diretoria-de-transpar-ncia-ativa---dta.md
> +[] [Repositório GitHub Dados MG](https://github.com/dados-mg)
[ ] Joomla
[ ] Mantis PRODEMGE
[ ] Fale Conosco (BPMS PRODEMGE)
[ ] Armazém B.O.

2021-04-27 15:07 UTC, gabrielbdornas commented on .github/ISSUE_TEMPLATE/onboarding-diretoria-de-transpar-ncia-ativa---dta.md
> +[] [Repositório GitHub Dados MG](https://github.com/dados-mg)
@Andrelamor, ótimas sugestões

2021-04-27 15:07 UTC, merged